name: mywinespace
favicon: null
layout_spectrum: 0.4885149176698178
typography_spectrum: 0.25429
title: mywinespace for wine lovers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3a3a42'
    - '#93173b'
    - '#aeadb1'
    - '#7e7e82'
  brandStrength: 0.5
  lightness: 0.9451298620551825
  saturation: 0.1571794229093939
  rhythmicContrast: 0.10364718828350306
purpose: []
