name: mywinespace
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28286
title: mywinespace for wine lovers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3a3a42'
    - '#94173b'
    - '#bebec0'
    - '#87868a'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
